### ISSUE TITLE
大佬你开源了一个寂寞

### ISSUE THREAD

**Issue by medasz** [zan8in/pyxis#1]
![image](https://user-images.githubusercontent.com/26796210/225797598-1775e508-5e42-4c3d-a581-573dc358caca.png)

https://github.com/zan8in/libra
不存在啊

**Comment by zan8in** [comment]
这个是指纹库，暂时不开源 ^O^

**Comment by medasz** [comment]
你自己写的啊？好吧

**Comment by medasz** [comment]
但是至少代码应该能跑，不能报错啊。。。。。。。。。
